#!/usr/bin/env python

import readline
import sqlite3
import config

con = sqlite3.connect(config.db)
cur = con.cursor()

#commands = ['station', 'system']

def completer(text, state):
	""" we get state from 0-3 and text contains the entered srting """
	#print state
	
		
	#options = [x for x in commands if x.startswith(text)]
	
	# we require at least 3 characters.
	if len(text) < 3:
		return None
	
	# do a database query, find all available systems
	sql = "SELECT name FROM system WHERE name LIKE '"+text+"%'"
	cur.execute(sql)
	res = cur.fetchall()
	options = []
	for name in res:
		#print "  %d, %s" % (id, val)
		options.append(name[0])
	
	try:
		return options[state]
	except IndexError:
		return None

readline.set_completer(completer)
readline.parse_and_bind("tab: complete")
readline.set_completer_delims(' \t\n...@#$%^&*()-=+[{]}\\|;:\'",<>?')

while 1:
    a = raw_input("> ")
    print "You entered", a
